source: ./
dest: ./build
posts: blog
drafts: _drafts
ignore: ["README.md", "build/*", ".git/*", "TODO.md", "_lunr", "*.md.noparse" ]
rss: rss.xml
name: booyaa's boggy bloggy
description: left intentionally blank
link: https://booyaa.wtf
