source: ./
dest: ./build
posts: blog
drafts: _drafts
ignore:
  - .git/*
  - build/*
  - README.md
  - TODO.md
  - "_lunr"
  - "*.md.noparse"
  - LICENSE-*
  - makefile
rss: rss.xml
name: booyaa's boggy bloggy
description: left intentionally blank
link: https://booyaa.wtf
